import type { Formula } from '../../../types';

export const fluidMechanicsFormulas: Formula[] = [
  {
    id: 'reynolds-number',
    name: 'Reynolds Number',
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'Re = ρvD / μ',
    description: 'Dimensionless number predicting whether fluid flow will be laminar or turbulent.',
    variables: [
      { symbol: 'Re', name: 'Reynolds number', unit: 'dimensionless' },
      { symbol: 'rho', name: 'Fluid density', unit: 'kg/m³' },
      { symbol: 'v', name: 'Flow velocity', unit: 'm/s' },
      { symbol: 'D', name: 'Characteristic diameter', unit: 'm' },
      { symbol: 'mu', name: 'Dynamic viscosity', unit: 'Pa·s' },
    ],
    keywords: ['reynolds number', 'laminar flow', 'turbulent flow', 'fluid mechanics', 'viscosity'],
    solve: {
      Re: (v) => (v.rho * v.v * v.D) / v.mu,
      rho: (v) => (v.Re * v.mu) / (v.v * v.D),
      v: (v) => (v.Re * v.mu) / (v.rho * v.D),
      D: (v) => (v.Re * v.mu) / (v.rho * v.v),
      mu: (v) => (v.rho * v.v * v.D) / v.Re,
    },
  },
  {
    id: 'darcy-weisbach-head-loss',
    name: 'Darcy-Weisbach Head Loss',
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'h_f = f(L/D)(v²/2g)',
    description: 'Calculates the head loss due to friction as fluid flows through a pipe.',
    variables: [
      { symbol: 'hf', name: 'Head loss', unit: 'm' },
      { symbol: 'f', name: 'Darcy friction factor', unit: 'dimensionless' },
      { symbol: 'L', name: 'Pipe length', unit: 'm' },
      { symbol: 'D', name: 'Pipe diameter', unit: 'm' },
      { symbol: 'v', name: 'Flow velocity', unit: 'm/s' },
      { symbol: 'g', name: 'Gravitational acceleration', unit: 'm/s²' },
    ],
    keywords: ['darcy-weisbach', 'head loss', 'pipe friction', 'fluid mechanics', 'friction factor'],
    solve: {
      hf: (v) => v.f * (v.L / v.D) * (v.v ** 2 / (2 * v.g)),
      f: (v) => (v.hf * v.D * 2 * v.g) / (v.L * v.v ** 2),
      L: (v) => (v.hf * v.D * 2 * v.g) / (v.f * v.v ** 2),
      D: (v) => (v.f * v.L * v.v ** 2) / (v.hf * 2 * v.g),
      v: (v) => {
        const val = (v.hf * v.D * 2 * v.g) / (v.f * v.L);
        if (val < 0) throw new Error('Cannot take the square root of a negative value for these inputs.');
        return Math.sqrt(val);
      },
      g: (v) => (v.f * v.L * v.v ** 2) / (v.hf * 2 * v.D),
    },
  },
  {
    id: 'drag-force',
    name: 'Drag Force',
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'F_d = ½ρv²C_dA',
    description: 'Calculates the drag force on an object moving through a fluid.',
    variables: [
      { symbol: 'Fd', name: 'Drag force', unit: 'N' },
      { symbol: 'rho', name: 'Fluid density', unit: 'kg/m³' },
      { symbol: 'v', name: 'Velocity', unit: 'm/s' },
      { symbol: 'Cd', name: 'Drag coefficient', unit: 'dimensionless' },
      { symbol: 'A', name: 'Reference area', unit: 'm²' },
    ],
    keywords: ['drag force', 'fluid mechanics', 'aerodynamics', 'drag coefficient'],
    solve: {
      Fd: (v) => 0.5 * v.rho * v.v ** 2 * v.Cd * v.A,
      rho: (v) => (2 * v.Fd) / (v.v ** 2 * v.Cd * v.A),
      v: (v) => {
        const val = (2 * v.Fd) / (v.rho * v.Cd * v.A);
        if (val < 0) throw new Error('Cannot take the square root of a negative value for these inputs.');
        return Math.sqrt(val);
      },
      Cd: (v) => (2 * v.Fd) / (v.rho * v.v ** 2 * v.A),
      A: (v) => (2 * v.Fd) / (v.rho * v.v ** 2 * v.Cd),
    },
  },
  {
    id: 'lift-force',
    name: 'Lift Force',
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'F_l = ½ρv²C_lA',
    description: 'Calculates the lift force generated by a body such as an airfoil moving through a fluid.',
    variables: [
      { symbol: 'Fl', name: 'Lift force', unit: 'N' },
      { symbol: 'rho', name: 'Fluid density', unit: 'kg/m³' },
      { symbol: 'v', name: 'Velocity', unit: 'm/s' },
      { symbol: 'Cl', name: 'Lift coefficient', unit: 'dimensionless' },
      { symbol: 'A', name: 'Reference area', unit: 'm²' },
    ],
    keywords: ['lift force', 'fluid mechanics', 'aerodynamics', 'lift coefficient', 'airfoil'],
    solve: {
      Fl: (v) => 0.5 * v.rho * v.v ** 2 * v.Cl * v.A,
      rho: (v) => (2 * v.Fl) / (v.v ** 2 * v.Cl * v.A),
      v: (v) => {
        const val = (2 * v.Fl) / (v.rho * v.Cl * v.A);
        if (val < 0) throw new Error('Cannot take the square root of a negative value for these inputs.');
        return Math.sqrt(val);
      },
      Cl: (v) => (2 * v.Fl) / (v.rho * v.v ** 2 * v.A),
      A: (v) => (2 * v.Fl) / (v.rho * v.v ** 2 * v.Cl),
    },
  },
  {
    id: 'volumetric-flow-rate',
    name: 'Volumetric Flow Rate',
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'Q = Av',
    description: 'Calculates the volumetric flow rate of a fluid through a cross-section from area and velocity.',
    variables: [
      { symbol: 'Q', name: 'Volumetric flow rate', unit: 'm³/s' },
      { symbol: 'A', name: 'Cross-sectional area', unit: 'm²' },
      { symbol: 'v', name: 'Flow velocity', unit: 'm/s' },
    ],
    keywords: ['volumetric flow rate', 'flow rate', 'fluid mechanics', 'discharge'],
    solve: {
      Q: (v) => v.A * v.v,
      A: (v) => v.Q / v.v,
      v: (v) => v.Q / v.A,
    },
  },
  {
    id: 'bernoulli-equation',
    name: "Bernoulli's Equation",
    category: 'Engineering',
    subcategory: 'Fluid Mechanics',
    equation: 'p₁ + ½ρv₁² + ρgh₁ = p₂ + ½ρv₂² + ρgh₂',
    description: 'Relates pressure, velocity, and elevation of a fluid between two points along a streamline, assuming no energy loss.',
    variables: [
      { symbol: 'p1', name: 'Pressure at point 1', unit: 'Pa' },
      { symbol: 'v1', name: 'Velocity at point 1', unit: 'm/s' },
      { symbol: 'h1', name: 'Elevation at point 1', unit: 'm' },
      { symbol: 'p2', name: 'Pressure at point 2', unit: 'Pa' },
      { symbol: 'v2', name: 'Velocity at point 2', unit: 'm/s' },
      { symbol: 'h2', name: 'Elevation at point 2', unit: 'm' },
      { symbol: 'rho', name: 'Fluid density', unit: 'kg/m³' },
      { symbol: 'g', name: 'Gravitational acceleration', unit: 'm/s²' },
    ],
    keywords: ['bernoulli equation', 'fluid mechanics', 'pressure', 'streamline', 'conservation of energy'],
    solve: {
      p1: (v) => v.p2 + 0.5 * v.rho * (v.v2 ** 2 - v.v1 ** 2) + v.rho * v.g * (v.h2 - v.h1),
      p2: (v) => v.p1 + 0.5 * v.rho * (v.v1 ** 2 - v.v2 ** 2) + v.rho * v.g * (v.h1 - v.h2),
      h1: (v) => (v.p2 - v.p1 + 0.5 * v.rho * (v.v2 ** 2 - v.v1 ** 2) + v.rho * v.g * v.h2) / (v.rho * v.g),
      h2: (v) => (v.p1 - v.p2 + 0.5 * v.rho * (v.v1 ** 2 - v.v2 ** 2) + v.rho * v.g * v.h1) / (v.rho * v.g),
      v1: (v) => {
        const val = v.v2 ** 2 + (2 * (v.p2 - v.p1)) / v.rho + 2 * v.g * (v.h2 - v.h1);
        if (val < 0) throw new Error('Cannot take the square root of a negative value for these inputs.');
        return Math.sqrt(val);
      },
      v2: (v) => {
        const val = v.v1 ** 2 + (2 * (v.p1 - v.p2)) / v.rho + 2 * v.g * (v.h1 - v.h2);
        if (val < 0) throw new Error('Cannot take the square root of a negative value for these inputs.');
        return Math.sqrt(val);
      },
      rho: (v) => (v.p1 - v.p2) / (0.5 * (v.v2 ** 2 - v.v1 ** 2) + v.g * (v.h2 - v.h1)),
      g: (v) => (v.p1 - v.p2 - 0.5 * v.rho * (v.v2 ** 2 - v.v1 ** 2)) / (v.rho * (v.h2 - v.h1)),
    },
  },
];
