"""Fluid mechanics formulas: Reynolds number, head loss, drag/lift, Bernoulli's equation."""

import math

from ...models.formula import Formula, Variable

FLUID_MECHANICS_FORMULAS: list[Formula] = []

FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="reynolds-number",
        name="Reynolds Number",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="Re = ρvD / μ",
        description="Dimensionless number predicting whether fluid flow will be laminar or turbulent.",
        variables=[
            Variable("Re", "Reynolds number", "dimensionless"),
            Variable("rho", "Fluid density", "kg/m³"),
            Variable("v", "Flow velocity", "m/s"),
            Variable("D", "Characteristic diameter", "m"),
            Variable("mu", "Dynamic viscosity", "Pa·s"),
        ],
        keywords=["reynolds number", "laminar flow", "turbulent flow", "fluid mechanics", "viscosity"],
        solve={
            "Re": lambda v: (v["rho"] * v["v"] * v["D"]) / v["mu"],
            "rho": lambda v: (v["Re"] * v["mu"]) / (v["v"] * v["D"]),
            "v": lambda v: (v["Re"] * v["mu"]) / (v["rho"] * v["D"]),
            "D": lambda v: (v["Re"] * v["mu"]) / (v["rho"] * v["v"]),
            "mu": lambda v: (v["rho"] * v["v"] * v["D"]) / v["Re"],
        },
    )
)


def _darcy_weisbach_v(v: dict[str, float]) -> float:
    val = (v["hf"] * v["D"] * 2 * v["g"]) / (v["f"] * v["L"])
    if val < 0:
        raise ValueError("Cannot take the square root of a negative value for these inputs.")
    return math.sqrt(val)


FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="darcy-weisbach-head-loss",
        name="Darcy-Weisbach Head Loss",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="h_f = f(L/D)(v²/2g)",
        description="Calculates the head loss due to friction as fluid flows through a pipe.",
        variables=[
            Variable("hf", "Head loss", "m"),
            Variable("f", "Darcy friction factor", "dimensionless"),
            Variable("L", "Pipe length", "m"),
            Variable("D", "Pipe diameter", "m"),
            Variable("v", "Flow velocity", "m/s"),
            Variable("g", "Gravitational acceleration", "m/s²"),
        ],
        keywords=["darcy-weisbach", "head loss", "pipe friction", "fluid mechanics", "friction factor"],
        solve={
            "hf": lambda v: v["f"] * (v["L"] / v["D"]) * (v["v"] ** 2 / (2 * v["g"])),
            "f": lambda v: (v["hf"] * v["D"] * 2 * v["g"]) / (v["L"] * v["v"] ** 2),
            "L": lambda v: (v["hf"] * v["D"] * 2 * v["g"]) / (v["f"] * v["v"] ** 2),
            "D": lambda v: (v["f"] * v["L"] * v["v"] ** 2) / (v["hf"] * 2 * v["g"]),
            "v": _darcy_weisbach_v,
            "g": lambda v: (v["f"] * v["L"] * v["v"] ** 2) / (v["hf"] * 2 * v["D"]),
        },
    )
)


def _drag_force_v(v: dict[str, float]) -> float:
    val = (2 * v["Fd"]) / (v["rho"] * v["Cd"] * v["A"])
    if val < 0:
        raise ValueError("Cannot take the square root of a negative value for these inputs.")
    return math.sqrt(val)


FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="drag-force",
        name="Drag Force",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="F_d = ½ρv²C_dA",
        description="Calculates the drag force on an object moving through a fluid.",
        variables=[
            Variable("Fd", "Drag force", "N"),
            Variable("rho", "Fluid density", "kg/m³"),
            Variable("v", "Velocity", "m/s"),
            Variable("Cd", "Drag coefficient", "dimensionless"),
            Variable("A", "Reference area", "m²"),
        ],
        keywords=["drag force", "fluid mechanics", "aerodynamics", "drag coefficient"],
        solve={
            "Fd": lambda v: 0.5 * v["rho"] * v["v"] ** 2 * v["Cd"] * v["A"],
            "rho": lambda v: (2 * v["Fd"]) / (v["v"] ** 2 * v["Cd"] * v["A"]),
            "v": _drag_force_v,
            "Cd": lambda v: (2 * v["Fd"]) / (v["rho"] * v["v"] ** 2 * v["A"]),
            "A": lambda v: (2 * v["Fd"]) / (v["rho"] * v["v"] ** 2 * v["Cd"]),
        },
    )
)


def _lift_force_v(v: dict[str, float]) -> float:
    val = (2 * v["Fl"]) / (v["rho"] * v["Cl"] * v["A"])
    if val < 0:
        raise ValueError("Cannot take the square root of a negative value for these inputs.")
    return math.sqrt(val)


FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="lift-force",
        name="Lift Force",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="F_l = ½ρv²C_lA",
        description="Calculates the lift force generated by a body such as an airfoil moving through a fluid.",
        variables=[
            Variable("Fl", "Lift force", "N"),
            Variable("rho", "Fluid density", "kg/m³"),
            Variable("v", "Velocity", "m/s"),
            Variable("Cl", "Lift coefficient", "dimensionless"),
            Variable("A", "Reference area", "m²"),
        ],
        keywords=["lift force", "fluid mechanics", "aerodynamics", "lift coefficient", "airfoil"],
        solve={
            "Fl": lambda v: 0.5 * v["rho"] * v["v"] ** 2 * v["Cl"] * v["A"],
            "rho": lambda v: (2 * v["Fl"]) / (v["v"] ** 2 * v["Cl"] * v["A"]),
            "v": _lift_force_v,
            "Cl": lambda v: (2 * v["Fl"]) / (v["rho"] * v["v"] ** 2 * v["A"]),
            "A": lambda v: (2 * v["Fl"]) / (v["rho"] * v["v"] ** 2 * v["Cl"]),
        },
    )
)

FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="volumetric-flow-rate",
        name="Volumetric Flow Rate",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="Q = Av",
        description="Calculates the volumetric flow rate of a fluid through a cross-section from area and velocity.",
        variables=[
            Variable("Q", "Volumetric flow rate", "m³/s"),
            Variable("A", "Cross-sectional area", "m²"),
            Variable("v", "Flow velocity", "m/s"),
        ],
        keywords=["volumetric flow rate", "flow rate", "fluid mechanics", "discharge"],
        solve={
            "Q": lambda v: v["A"] * v["v"],
            "A": lambda v: v["Q"] / v["v"],
            "v": lambda v: v["Q"] / v["A"],
        },
    )
)


def _bernoulli_v1(v: dict[str, float]) -> float:
    val = v["v2"] ** 2 + (2 * (v["p2"] - v["p1"])) / v["rho"] + 2 * v["g"] * (v["h2"] - v["h1"])
    if val < 0:
        raise ValueError("Cannot take the square root of a negative value for these inputs.")
    return math.sqrt(val)


def _bernoulli_v2(v: dict[str, float]) -> float:
    val = v["v1"] ** 2 + (2 * (v["p1"] - v["p2"])) / v["rho"] + 2 * v["g"] * (v["h1"] - v["h2"])
    if val < 0:
        raise ValueError("Cannot take the square root of a negative value for these inputs.")
    return math.sqrt(val)


FLUID_MECHANICS_FORMULAS.append(
    Formula(
        id="bernoulli-equation",
        name="Bernoulli's Equation",
        category="Engineering",
        subcategory="Fluid Mechanics",
        equation="p₁ + ½ρv₁² + ρgh₁ = p₂ + ½ρv₂² + ρgh₂",
        description="Relates pressure, velocity, and elevation of a fluid between two points along a streamline, assuming no energy loss.",
        variables=[
            Variable("p1", "Pressure at point 1", "Pa"),
            Variable("v1", "Velocity at point 1", "m/s"),
            Variable("h1", "Elevation at point 1", "m"),
            Variable("p2", "Pressure at point 2", "Pa"),
            Variable("v2", "Velocity at point 2", "m/s"),
            Variable("h2", "Elevation at point 2", "m"),
            Variable("rho", "Fluid density", "kg/m³"),
            Variable("g", "Gravitational acceleration", "m/s²"),
        ],
        keywords=["bernoulli equation", "fluid mechanics", "pressure", "streamline", "conservation of energy"],
        solve={
            "p1": lambda v: v["p2"] + 0.5 * v["rho"] * (v["v2"] ** 2 - v["v1"] ** 2) + v["rho"] * v["g"] * (v["h2"] - v["h1"]),
            "p2": lambda v: v["p1"] + 0.5 * v["rho"] * (v["v1"] ** 2 - v["v2"] ** 2) + v["rho"] * v["g"] * (v["h1"] - v["h2"]),
            "h1": lambda v: (v["p2"] - v["p1"] + 0.5 * v["rho"] * (v["v2"] ** 2 - v["v1"] ** 2) + v["rho"] * v["g"] * v["h2"]) / (v["rho"] * v["g"]),
            "h2": lambda v: (v["p1"] - v["p2"] + 0.5 * v["rho"] * (v["v1"] ** 2 - v["v2"] ** 2) + v["rho"] * v["g"] * v["h1"]) / (v["rho"] * v["g"]),
            "v1": _bernoulli_v1,
            "v2": _bernoulli_v2,
            "rho": lambda v: (v["p1"] - v["p2"]) / (0.5 * (v["v2"] ** 2 - v["v1"] ** 2) + v["g"] * (v["h2"] - v["h1"])),
            "g": lambda v: (v["p1"] - v["p2"] - 0.5 * v["rho"] * (v["v2"] ** 2 - v["v1"] ** 2)) / (v["rho"] * (v["h2"] - v["h1"])),
        },
    )
)
